const IMG=window.SURI_IMG || {};
const CUE={
 'Cat–cow':'Move slowly through a comfortable range. Think segment-by-segment rather than forcing the deepest arch or round.',
 'Open-book thoracic rotation':'Keep knees stacked. Let the motion come mostly from the upper back and ribcage, not by cranking the low back.',
 '90/90 hip switches':'Stay tall and rotate smoothly through the hips. Use your hands for support if needed.',
 'Half-kneeling hip-flexor stretch':'Lightly squeeze the glute on the kneeling side, keep ribs stacked, then glide forward only until a gentle front-of-hip stretch.',
 'Adductor rock-backs':'Keep a neutral spine, one leg out to the side, and send the hips back until you feel the inner thigh—not a pinch.',
 'Diagonal child’s-pose reach':'Reach long on a diagonal and breathe into the side of the ribcage and upper back.',
 'Cable row':'Chest tall, ribs controlled, elbows close. Pull toward the torso without shrugging or leaning backward.',
 'Face pull':'Use a light load. Pull the rope toward eye level and keep the shoulders away from the ears.',
 'Pallof press':'Brace, press straight out and resist the cable trying to rotate you. Keep ribs over pelvis.',
 'Bird dog':'Move opposite arm and leg slowly without letting the pelvis twist or the low back sag.',
 'Glute bridge':'Drive through the feet and finish with the glutes. Stop before the low back starts doing the work.',
 'Cable external rotation':'Very light load. Keep elbow tucked at roughly 90 degrees and rotate the forearm outward from the shoulder.',
 'Goblet squat':'Hold the weight close to the chest. Sit between the hips, keep the whole foot planted, and stop at a comfortable depth.',
 'Dumbbell bench press':'Shoulder blades supported, feet planted, wrists stacked over elbows. Leave reps in reserve.',
 'Chest-supported dumbbell row':'Let the bench support your torso. Pull the elbows back without shrugging.',
 'Dumbbell Romanian deadlift':'Hinge at the hips with soft knees. Keep weights close and stop before your low back rounds or tightens.',
 'Standing calf raise':'Rise smoothly through the ball of the foot, pause at the top, and lower under control.',
 'Rear-foot-elevated split squat':'Use a stance that lets the front foot stay planted. Descend vertically and avoid chasing maximum depth.',
 'Incline dumbbell press':'Keep the ribcage controlled and press without shrugging the shoulders toward the ears.',
 'Neutral-grip lat pulldown':'Pull elbows down toward the ribs while keeping the chest tall and avoiding excessive lean-back.',
 'Hip thrust':'Tuck the ribs, drive through the heels, and finish with glutes instead of hyperextending the low back.',
 'Side plank':'Make a straight line from shoulder to hip to ankle/knee and keep breathing behind the brace.',
 'Step-up':'Use the working leg to drive onto the box. Avoid pushing off aggressively with the trailing foot.',
 'Golf-stance hip rotations':'Soft knees, athletic posture. Rotate through the hips while keeping the movement smooth and controlled.',
 'Standing thoracic rotations with club':'Club across the shoulders. Rotate the upper back without forcing the low back.',
 'Slow practice swings':'Full but easy motion. Prioritize balance, sequence, and range rather than speed.',
 '60% swings':'Smooth tempo at about 60% effort. Finish balanced.',
 '75% swings':'Increase speed slightly but stop well short of max effort.'
};
const plans={
 7:{tag:'Strength',title:'Full-body strength A',sub:'Your best day for meaningful loading',time:'45–55 min',effort:'RPE 6–7',intro:'Leave 2–4 reps in reserve. Build strength without making your back negotiate every rep.',note:'Rest 75–120 sec on main lifts; 45–60 sec on accessories.',sections:[['Warm-up',[['Bike or incline walk','5 min'],['Cat–cow','8'],['90/90 hip switches','8/side'],['Open-book thoracic rotation','6/side']]],['Strength',[['Goblet squat','3 × 8'],['Dumbbell bench press','3 × 8–10'],['Chest-supported dumbbell row','3 × 10'],['Dumbbell Romanian deadlift','2 × 8 • moderate'],['Pallof press','2 × 10/side'],['Standing calf raise','2 × 15']]]]},
 6:{tag:'Recovery',title:'Mobility + aerobic base',sub:'Recover while keeping capacity',time:'30–45 min',effort:'Easy',intro:'Create movement options in the hips and upper back without chasing soreness.',sections:[['Aerobic',[['Bike, incline treadmill or elliptical','20–30 min easy']]],['Mobility',[['Cat–cow','2 × 8'],['Open-book thoracic rotation','2 × 8/side'],['90/90 hip switches','2 × 8/side'],['Half-kneeling hip-flexor stretch','2 × 30 sec/side'],['Adductor rock-backs','2 × 8/side']]],['Core',[['Bird dog','2 × 6/side'],['Pallof press','2 × 10/side']]]]},
 5:{tag:'Strength',title:'Full-body strength B',sub:'Second real strength day',time:'45–55 min',effort:'RPE 6–7',intro:'Legs, upper back, pressing and glutes without aggressive spinal loading.',note:'If split squats make you sore for days, switch to reverse lunges or step-ups.',sections:[['Warm-up',[['Bike or walk','5 min'],['90/90 hip switches','8/side'],['Open-book thoracic rotation','6/side']]],['Strength',[['Rear-foot-elevated split squat','3 × 8/side'],['Incline dumbbell press','3 × 8–10'],['Neutral-grip lat pulldown','3 × 10'],['Hip thrust','3 × 10'],['Face pull','2 × 15'],['Side plank','2 × 20–30 sec/side']]]]},
 4:{tag:'Recovery',title:'Easy conditioning + mobility',sub:'Keep capacity, reduce stiffness',time:'30–40 min',effort:'Easy–moderate',intro:'Finish fresher than you started.',sections:[['Conditioning',[['Bike or incline walk','20–25 min']]],['Mobility • 2 rounds',[['Open-book thoracic rotation','8/side'],['90/90 hip switches','8/side'],['Adductor rock-backs','8/side'],['Diagonal child’s-pose reach','30 sec/side']]],['Activation',[['Face pull','2 × 12'],['Bird dog','2 × 6/side']]]]},
 3:{tag:'Primer',title:'Strength primer',sub:'Keep the nervous system sharp',time:'30–40 min',effort:'RPE 5–6',intro:'This is training, not testing. Avoid anything that reliably creates 48-hour soreness.',sections:[['Strength',[['Goblet squat','2 × 8'],['Cable row','2 × 10'],['Dumbbell bench press','2 × 10'],['Step-up','2 × 8/side'],['Pallof press','2 × 10/side'],['Face pull','2 × 12–15']]],['Mobility',[['Open-book thoracic rotation','1 × 8/side'],['Half-kneeling hip-flexor stretch','30 sec/side']]]]},
 2:{tag:'Golf prep',title:'Mobility + activation',sub:'No soreness tax from here',time:'25–35 min',effort:'Light',intro:'Prioritize hips, upper back, trunk control and shoulders. Skip heavy lower-body work.',sections:[['Mobility • 2 rounds',[['Cat–cow','8'],['Open-book thoracic rotation','8/side'],['90/90 hip switches','8/side'],['Adductor rock-backs','8/side']]],['Activation',[['Cable row','2 × 12'],['Pallof press','2 × 10/side'],['Bird dog','2 × 6/side'],['Glute bridge','2 × 12'],['Cable external rotation','2 × 12/side']]]]},
 1:{tag:'Day before',title:'Golf mobility + activation',sub:'Leave the gym looser than you entered',time:'35–40 min',effort:'RPE 5–6',intro:'No heavy deadlifts, squats, bent-over rows or hard rotational power work today.',note:'Rest 30–45 sec. The objective is readiness, not fatigue.',sections:[['Warm-up',[['Incline treadmill or easy bike','5 min']]],['Back + hip mobility • 2 rounds',[['Cat–cow','8 slow'],['Open-book thoracic rotation','8/side'],['90/90 hip switches','8/side'],['Half-kneeling hip-flexor stretch','30 sec/side'],['Adductor rock-backs','8/side'],['Diagonal child’s-pose reach','30 sec/side']]],['Golf activation',[['Cable row','2 × 12'],['Face pull','2 × 12–15'],['Pallof press','2 × 10/side • 2-sec hold'],['Bird dog','2 × 6/side'],['Glute bridge','2 × 12'],['Cable external rotation','2 × 12/side']]],['Golf-specific movement',[['Golf-stance hip rotations','10 each direction'],['Standing thoracic rotations with club','8/side'],['Slow practice swings','5'],['60% swings','5'],['75% swings','3']]]]},
 0:{tag:'Golf day',title:'Golf-day warm-up',sub:'Short, dynamic, no gym fatigue',time:'8–12 min',effort:'Easy',intro:'Get warm before full swings. Avoid long static stretching immediately before teeing off.',sections:[['Get warm',[['Brisk walk','2–3 min'],['Hip circles','8 each direction'],['Arm circles','10 each direction']]],['Move',[['Golf-stance hip rotations','8 each direction'],['Standing thoracic rotations with club','8/side'],['Bodyweight squat to comfortable depth','8']]],['Ramp swings',[['Slow practice swings','5'],['60% swings','5'],['75% swings','3–5']]]]}
};
const library={mobility:[['Cat–cow','2 × 8 slow'],['Open-book thoracic rotation','2 × 8/side'],['90/90 hip switches','2 × 8/side'],['Half-kneeling hip-flexor stretch','2 × 30 sec/side'],['Adductor rock-backs','2 × 8/side'],['Diagonal child’s-pose reach','2 × 30 sec/side']],activation:[['Cable row','2 × 12'],['Face pull','2 × 12–15'],['Pallof press','2 × 10/side'],['Bird dog','2 × 6/side'],['Glute bridge','2 × 12'],['Cable external rotation','2 × 12/side']]};
const week=[['MON','Strength A','Full body · RPE 6–7','Strength'],['TUE','Mobility + cardio','30–45 min','Recovery'],['WED','Strength B','Full body · RPE 6–7','Strength'],['THU','Recovery / walking','Keep it easy','Recovery'],['FRI','Primer / upper body','Low–moderate volume','Primer'],['SAT','Long easy activity','Bike, walk, golf, etc.','Activity'],['SUN','Recovery + mobility','10–20 min','Recovery']];
let day=Number(localStorage.getItem('suri-golf-day') ?? 1);let completed=JSON.parse(localStorage.getItem('suri-golf-done')||'{}');let libTab='mobility';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function totalFor(p){return p.sections.reduce((n,s)=>n+s[1].length,0)}
function doneForDay(){return Object.keys(completed).filter(k=>k.startsWith(day+'-')&&completed[k]).length}
function renderDays(){const labels={0:'Today',1:'1 day',2:'2 days',3:'3 days',4:'4 days',5:'5 days',6:'6 days',7:'7 days'};$('#days').innerHTML=[7,6,5,4,3,2,1,0].map(d=>`<button class="day-pill ${d===day?'active':''}" data-day="${d}">${labels[d]}</button>`).join('');$('#bigDay').textContent=day===0?'Golf today':day===1?'1 day':`${day} days`;$('#modeBadge').textContent=plans[day].tag;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{day=Number(b.dataset.day);localStorage.setItem('suri-golf-day',day);renderDays();renderPlan();window.scrollTo({top:0,behavior:'smooth'})})}
function exRow(name,dose,key){const img=IMG[name];const cue=CUE[name]||'Move smoothly through a comfortable range and stop if symptoms worsen.';const photo=img?`<div class="photo-preview" aria-hidden="true"><img class="thumb" src="${img}" alt=""><span>↗</span></div>`:`<div class="glyph" aria-hidden="true">${esc(name.split(' ').map(x=>x[0]).join('').slice(0,2))}</div>`;const isDone=completed[key];return `<div class="exercise ${img?'':'no-img'} ${isDone?'done':''}" data-key="${key}" data-name="${esc(name)}" data-dose="${esc(dose)}"><button class="exercise-open" type="button" aria-label="View ${esc(name)} exercise details">${photo}<span><span class="exercise-name">${esc(name)}</span><span class="exercise-dose">${esc(dose)}</span><span class="exercise-cue">${esc(cue)}</span></span></button><button class="check-button" type="button" aria-label="Mark ${esc(name)} ${isDone?'incomplete':'complete'}" aria-pressed="${isDone?'true':'false'}"><span class="check" aria-hidden="true">✓</span></button></div>`}
function renderPlan(){const p=plans[day];const total=totalFor(p),done=doneForDay(),pct=Math.round(done/total*100);$('#planTime').textContent=p.time;$('#planCard').innerHTML=`<div class="plan-head"><div class="badges"><span class="badge primary">${esc(p.tag)}</span><span class="badge">◷ ${esc(p.time)}</span><span class="badge">↯ ${esc(p.effort)}</span></div><h2>${esc(p.title)}</h2><p>${esc(p.sub)}. ${esc(p.intro)}</p><div class="progress-wrap"><div class="progress-meta"><span>${done} / ${total} complete</span><span>${pct}%</span></div><div class="progress"><i style="width:${pct}%"></i></div></div></div>${p.sections.map((s,si)=>`<div class="work-section"><div class="work-title"><b>${esc(s[0])}</b><span>${s[1].length} items</span></div><div class="exercise-list">${s[1].map((x,ei)=>exRow(x[0],x[1],`${day}-${si}-${ei}`)).join('')}</div></div>`).join('')}${p.note?`<div class="work-section"><div class="callout">${esc(p.note)}</div></div>`:''}`;document.querySelectorAll('#planCard .exercise').forEach(row=>{row.querySelector('.exercise-open').onclick=()=>openDetail(row.dataset.name,row.dataset.dose);row.querySelector('.check-button').onclick=()=>{const key=row.dataset.key;completed[key]=!completed[key];localStorage.setItem('suri-golf-done',JSON.stringify(completed));renderPlan()}})}
function renderLibrary(){const data=library[libTab];$('#libraryList').innerHTML=data.map(([n,d])=>`<div class="lib-row" data-lib-name="${esc(n)}" data-lib-dose="${esc(d)}">${IMG[n]?`<img src="${IMG[n]}" alt="${esc(n)}">`:`<div class="glyph">${esc(n.split(' ').map(x=>x[0]).join('').slice(0,2))}</div>`}<div><b>${esc(n)}</b><small>${esc(d)}</small></div><div class="chev">›</div></div>`).join('');document.querySelectorAll('.lib-row').forEach(r=>r.onclick=()=>openDetail(r.dataset.libName,r.dataset.libDose));document.querySelectorAll('[data-lib]').forEach(b=>b.classList.toggle('active',b.dataset.lib===libTab))}
function renderWeek(){$('#weekList').innerHTML=week.map(r=>`<div class="week-row"><div class="dow">${r[0]}</div><div><b>${r[1]}</b><small>${r[2]}</small></div><div class="week-type">${r[3]}</div></div>`).join('')}
function openDetail(name,dose){$('#sheetTitle').textContent=name;$('#sheetDose').textContent=dose;$('#sheetCue').textContent=CUE[name]||'Move smoothly through a comfortable range. Stop if symptoms worsen.';const img=IMG[name];$('#sheetImg').style.display=img?'block':'none';if(img){$('#sheetImg').src=img;$('#sheetImg').alt=`${name} exercise demonstration`}$('#detailSheet').classList.add('open');$('#backdrop').classList.add('open');$('#detailSheet').setAttribute('aria-hidden','false');document.body.classList.add('sheet-open')}
function closeSheet(){$('#detailSheet').classList.remove('open');$('#backdrop').classList.remove('open');$('#detailSheet').setAttribute('aria-hidden','true');document.body.classList.remove('sheet-open')}
function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('#'+name+'Screen').classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>showScreen(n.dataset.screen));document.querySelectorAll('[data-lib]').forEach(b=>b.onclick=()=>{libTab=b.dataset.lib;renderLibrary()});$('#closeSheet').onclick=closeSheet;$('#backdrop').onclick=closeSheet;$('#resetBtn').onclick=()=>{completed={};localStorage.setItem('suri-golf-done','{}');renderPlan()};
renderDays();renderPlan();renderLibrary();renderWeek();
